version: '3'

services:
  # Database
  mysql:
    image: mysql:8.2
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: procapi
      MYSQL_DATABASE: procapi
      MYSQL_USER: procapi
      MYSQL_PASSWORD: procapi
    networks:
      - procapi

networks:
  procapi:

# volumes секция больше не нужна
