version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - procapi
    env_file:
      - .env

  api:
    container_name: api
    image: api
    depends_on:
      - mysql
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - procapi
    volumes:
      - ./app:/app
    command: sh -c "pip install --upgrade pip && pip install -r requirements.txt && python app.py"
    env_file:
      - .env

  # Database
  mysql:
    image: mysql:8.2
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - procapi
    env_file:
      - .env

networks:
  procapi:
